//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GolfCentra.Core.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class BlockSlot
    {
        public long BlockSlotId { get; set; }
        public long BlockSlotRangeId { get; set; }
        public long SlotSessionWiseId { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
    
        public virtual BlockSlotRange BlockSlotRange { get; set; }
        public virtual SlotSessionWise SlotSessionWise { get; set; }
    }
}
