//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GolfCentra.Core.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class BlockSlotRange
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BlockSlotRange()
        {
            this.BlockSlots = new HashSet<BlockSlot>();
        }
    
        public long BlockSlotRangeId { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public long SlotBlockReasonId { get; set; }
        public Nullable<long> CoursePairingId { get; set; }
        public bool IsCustomerAvailable { get; set; }
        public bool IsBookingavailable { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public string Reason { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BlockSlot> BlockSlots { get; set; }
        public virtual CoursePairing CoursePairing { get; set; }
        public virtual SlotBlockReason SlotBlockReason { get; set; }
    }
}
