//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GolfCentra.Core.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class BookingPlayerMapping
    {
        public long BookingPlayerMappingId { get; set; }
        public long BookingId { get; set; }
        public long MemberTypeId { get; set; }
        public string MemberTypeName { get; set; }
        public int PlayerCount { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
    
        public virtual Booking Booking { get; set; }
        public virtual MemberType MemberType { get; set; }
    }
}
