//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GolfCentra.Core.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class BucketDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BucketDetail()
        {
            this.BucketTaxMappings = new HashSet<BucketTaxMapping>();
        }
    
        public long BucketDetailId { get; set; }
        public int Balls { get; set; }
        public decimal Price { get; set; }
        public Nullable<long> CurrencyId { get; set; }
        public Nullable<long> DayTypeId { get; set; }
        public Nullable<long> MemberTypeId { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
    
        public virtual Currency Currency { get; set; }
        public virtual DayType DayType { get; set; }
        public virtual MemberType MemberType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BucketTaxMapping> BucketTaxMappings { get; set; }
    }
}
