//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GolfCentra.Core.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Course
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Course()
        {
            this.CourseTaxMappings = new HashSet<CourseTaxMapping>();
        }
    
        public long CourseId { get; set; }
        public string CourseName { get; set; }
        public string Address { get; set; }
        public string TechnicalSupportMailId { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public string Latitude { get; set; }
        public string Longitude { get; set; }
        public string ShortDescription { get; set; }
        public string LongDescription { get; set; }
        public string ImgUrl { get; set; }
        public Nullable<long> HoleTypeId { get; set; }
        public string TermsConditionPageURL { get; set; }
        public string PrivacyPolicyPageURL { get; set; }
        public string RuleAndRegulationURL { get; set; }
        public string Address2Name { get; set; }
        public string Address2 { get; set; }
        public string Address2Phone { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
    
        public virtual HoleType HoleType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CourseTaxMapping> CourseTaxMappings { get; set; }
    }
}
