//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GolfCentra.Core.DataBase
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GolfCentraEntities : DbContext
    {
        public GolfCentraEntities()
            : base("name=GolfCentraEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AboutU> AboutUs { get; set; }
        public virtual DbSet<Action> Actions { get; set; }
        public virtual DbSet<ActionRight> ActionRights { get; set; }
        public virtual DbSet<APIClient> APIClients { get; set; }
        public virtual DbSet<AppVersion> AppVersions { get; set; }
        public virtual DbSet<BlockSlot> BlockSlots { get; set; }
        public virtual DbSet<BlockSlotRange> BlockSlotRanges { get; set; }
        public virtual DbSet<Booking> Bookings { get; set; }
        public virtual DbSet<BookingCourseTaxMapping> BookingCourseTaxMappings { get; set; }
        public virtual DbSet<BookingEquipmentMapping> BookingEquipmentMappings { get; set; }
        public virtual DbSet<BookingPlayerDetail> BookingPlayerDetails { get; set; }
        public virtual DbSet<BookingPlayerMapping> BookingPlayerMappings { get; set; }
        public virtual DbSet<BookingStatu> BookingStatus { get; set; }
        public virtual DbSet<BookingType> BookingTypes { get; set; }
        public virtual DbSet<BucketDetail> BucketDetails { get; set; }
        public virtual DbSet<BucketTaxMapping> BucketTaxMappings { get; set; }
        public virtual DbSet<Country> Countries { get; set; }
        public virtual DbSet<Coupon> Coupons { get; set; }
        public virtual DbSet<CouponType> CouponTypes { get; set; }
        public virtual DbSet<Course> Courses { get; set; }
        public virtual DbSet<CourseName> CourseNames { get; set; }
        public virtual DbSet<CoursePairing> CoursePairings { get; set; }
        public virtual DbSet<CourseTaxMapping> CourseTaxMappings { get; set; }
        public virtual DbSet<Currency> Currencies { get; set; }
        public virtual DbSet<DayType> DayTypes { get; set; }
        public virtual DbSet<Employee> Employees { get; set; }
        public virtual DbSet<EmployeeType> EmployeeTypes { get; set; }
        public virtual DbSet<Equipment> Equipments { get; set; }
        public virtual DbSet<EquipmentTaxMapping> EquipmentTaxMappings { get; set; }
        public virtual DbSet<ErrorLog> ErrorLogs { get; set; }
        public virtual DbSet<ErrorType> ErrorTypes { get; set; }
        public virtual DbSet<FeeCategory> FeeCategories { get; set; }
        public virtual DbSet<GenderType> GenderTypes { get; set; }
        public virtual DbSet<Golfer> Golfers { get; set; }
        public virtual DbSet<GolferNotification> GolferNotifications { get; set; }
        public virtual DbSet<GolferPasswordChange> GolferPasswordChanges { get; set; }
        public virtual DbSet<HoleInformation> HoleInformations { get; set; }
        public virtual DbSet<HoleNumber> HoleNumbers { get; set; }
        public virtual DbSet<HoleTeeYardage> HoleTeeYardages { get; set; }
        public virtual DbSet<HoleType> HoleTypes { get; set; }
        public virtual DbSet<LogInHistory> LogInHistories { get; set; }
        public virtual DbSet<LogInStatu> LogInStatus { get; set; }
        public virtual DbSet<MaritalStatu> MaritalStatus { get; set; }
        public virtual DbSet<MemberType> MemberTypes { get; set; }
        public virtual DbSet<NationalHoliday> NationalHolidays { get; set; }
        public virtual DbSet<Page> Pages { get; set; }
        public virtual DbSet<PageRight> PageRights { get; set; }
        public virtual DbSet<ParStorke> ParStorkes { get; set; }
        public virtual DbSet<PaymentGatewayControl> PaymentGatewayControls { get; set; }
        public virtual DbSet<PaymentStatu> PaymentStatus { get; set; }
        public virtual DbSet<PlatformType> PlatformTypes { get; set; }
        public virtual DbSet<PriceTaxMapping> PriceTaxMappings { get; set; }
        public virtual DbSet<Pricing> Pricings { get; set; }
        public virtual DbSet<Promotion> Promotions { get; set; }
        public virtual DbSet<PromotionsEquipmentMapping> PromotionsEquipmentMappings { get; set; }
        public virtual DbSet<PromotionsTaxMapping> PromotionsTaxMappings { get; set; }
        public virtual DbSet<RuleAndRegulation> RuleAndRegulations { get; set; }
        public virtual DbSet<Salutation> Salutations { get; set; }
        public virtual DbSet<Score> Scores { get; set; }
        public virtual DbSet<ScoreHole1> ScoreHole1 { get; set; }
        public virtual DbSet<ScoreHole10> ScoreHole10 { get; set; }
        public virtual DbSet<ScoreHole11> ScoreHole11 { get; set; }
        public virtual DbSet<ScoreHole12> ScoreHole12 { get; set; }
        public virtual DbSet<ScoreHole13> ScoreHole13 { get; set; }
        public virtual DbSet<ScoreHole14> ScoreHole14 { get; set; }
        public virtual DbSet<ScoreHole15> ScoreHole15 { get; set; }
        public virtual DbSet<ScoreHole16> ScoreHole16 { get; set; }
        public virtual DbSet<ScoreHole17> ScoreHole17 { get; set; }
        public virtual DbSet<ScoreHole18> ScoreHole18 { get; set; }
        public virtual DbSet<ScoreHole19> ScoreHole19 { get; set; }
        public virtual DbSet<ScoreHole2> ScoreHole2 { get; set; }
        public virtual DbSet<ScoreHole20> ScoreHole20 { get; set; }
        public virtual DbSet<ScoreHole21> ScoreHole21 { get; set; }
        public virtual DbSet<ScoreHole22> ScoreHole22 { get; set; }
        public virtual DbSet<ScoreHole23> ScoreHole23 { get; set; }
        public virtual DbSet<ScoreHole24> ScoreHole24 { get; set; }
        public virtual DbSet<ScoreHole25> ScoreHole25 { get; set; }
        public virtual DbSet<ScoreHole26> ScoreHole26 { get; set; }
        public virtual DbSet<ScoreHole27> ScoreHole27 { get; set; }
        public virtual DbSet<ScoreHole3> ScoreHole3 { get; set; }
        public virtual DbSet<ScoreHole4> ScoreHole4 { get; set; }
        public virtual DbSet<ScoreHole5> ScoreHole5 { get; set; }
        public virtual DbSet<ScoreHole6> ScoreHole6 { get; set; }
        public virtual DbSet<ScoreHole7> ScoreHole7 { get; set; }
        public virtual DbSet<ScoreHole8> ScoreHole8 { get; set; }
        public virtual DbSet<ScoreHole9> ScoreHole9 { get; set; }
        public virtual DbSet<Session> Sessions { get; set; }
        public virtual DbSet<SessionActivity> SessionActivities { get; set; }
        public virtual DbSet<SessionActivityPage> SessionActivityPages { get; set; }
        public virtual DbSet<Slot> Slots { get; set; }
        public virtual DbSet<SlotBlockReason> SlotBlockReasons { get; set; }
        public virtual DbSet<SlotSessionWise> SlotSessionWises { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<Tax> Taxes { get; set; }
        public virtual DbSet<Tee> Tees { get; set; }
        public virtual DbSet<TimeFormat> TimeFormats { get; set; }
        public virtual DbSet<UserType> UserTypes { get; set; }
    }
}
