//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GolfCentra.Core.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Golfer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Golfer()
        {
            this.Bookings = new HashSet<Booking>();
            this.Scores = new HashSet<Score>();
        }
    
        public long GolferId { get; set; }
        public string Name { get; set; }
        public string LastName { get; set; }
        public string Email { get; set; }
        public string PhoneCode { get; set; }
        public string Mobile { get; set; }
        public string ClubMemberId { get; set; }
        public string Password { get; set; }
        public string ImgURL { get; set; }
        public long PlatformTypeId { get; set; }
        public string VerficationCode { get; set; }
        public string Age { get; set; }
        public Nullable<long> GenderTypeId { get; set; }
        public Nullable<long> MemberTypeId { get; set; }
        public Nullable<System.DateTime> MemberSince { get; set; }
        public string Occpoution { get; set; }
        public string SpouseName { get; set; }
        public Nullable<long> MaritalStatusId { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public string SpecialComments { get; set; }
        public Nullable<int> LoginAttempt { get; set; }
        public Nullable<bool> IsBlocked { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public string Address { get; set; }
        public Nullable<long> SalutationId { get; set; }
        public Nullable<bool> IsPrimaryPasswordChanged { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Booking> Bookings { get; set; }
        public virtual GenderType GenderType { get; set; }
        public virtual MaritalStatu MaritalStatu { get; set; }
        public virtual MemberType MemberType { get; set; }
        public virtual PlatformType PlatformType { get; set; }
        public virtual Salutation Salutation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Score> Scores { get; set; }
    }
}
