//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GolfCentra.Core.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class GolferPasswordChange
    {
        public long GolferPasswordChangeId { get; set; }
        public long GolferId { get; set; }
        public bool IsUsed { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime Createdon { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
    }
}
