//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GolfCentra.Core.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class HoleInformation
    {
        public long HoleInformationId { get; set; }
        public long HoleNumberId { get; set; }
        public decimal Latitude { get; set; }
        public decimal Longitude { get; set; }
        public string ImgUrl { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public string HoleName { get; set; }
        public Nullable<long> CourseNameId { get; set; }
    
        public virtual CourseName CourseName { get; set; }
        public virtual HoleNumber HoleNumber { get; set; }
    }
}
