//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GolfCentra.Core.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class LogInHistory
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LogInHistory()
        {
            this.SessionActivities = new HashSet<SessionActivity>();
        }
    
        public long LoginHistoryId { get; set; }
        public long UserId { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public Nullable<long> LoginStatusId { get; set; }
        public string Country { get; set; }
        public string CountryCode { get; set; }
        public string ISP { get; set; }
        public string Latitude { get; set; }
        public string Longitude { get; set; }
        public string ORG { get; set; }
        public string Region { get; set; }
        public string RegionName { get; set; }
        public string TimeZone { get; set; }
        public Nullable<int> ZipCode { get; set; }
        public string Status { get; set; }
        public string IPAddress { get; set; }
        public string MACAddress { get; set; }
        public string OperatingSystem { get; set; }
        public string UserAgent { get; set; }
        public string BrowserName { get; set; }
        public string BrowserVersion { get; set; }
        public string As { get; set; }
        public string City { get; set; }
        public Nullable<System.DateTime> LoggedOutAt { get; set; }
        public Nullable<long> UserTypeId { get; set; }
        public Nullable<long> PlatformTypeId { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public string DeviceTokenId { get; set; }
        public Nullable<int> ChangePasswordAttempt { get; set; }
    
        public virtual LogInStatu LogInStatu { get; set; }
        public virtual PlatformType PlatformType { get; set; }
        public virtual UserType UserType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SessionActivity> SessionActivities { get; set; }
    }
}
