//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GolfCentra.Core.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaymentGatewayControl
    {
        public long PaymentGatewayControlId { get; set; }
        public bool PaymentGatewayEnable { get; set; }
        public bool GreenFee { get; set; }
        public bool CartFee { get; set; }
        public bool CaddieFee { get; set; }
        public string EquipmentOffIds { get; set; }
        public bool AllMembers { get; set; }
        public string SelectedGolferIds { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
    }
}
