//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GolfCentra.Core.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pricing
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Pricing()
        {
            this.PriceTaxMappings = new HashSet<PriceTaxMapping>();
        }
    
        public long PricingId { get; set; }
        public long MemberTypeId { get; set; }
        public long BookingTypeId { get; set; }
        public Nullable<long> DayTypeId { get; set; }
        public Nullable<long> HoleTypeId { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public Nullable<decimal> GreenFee { get; set; }
        public Nullable<decimal> TaxAndFee { get; set; }
        public Nullable<decimal> AddOnCart { get; set; }
        public Nullable<decimal> AddOnCaddie { get; set; }
        public Nullable<decimal> ConvenienceFee { get; set; }
        public Nullable<decimal> RangeFee { get; set; }
        public Nullable<decimal> BucketFeePerPlayer { get; set; }
        public Nullable<int> NumberOfAllowedSessions { get; set; }
        public Nullable<long> SlotId { get; set; }
        public Nullable<long> CurrencyId { get; set; }
        public Nullable<bool> IsSpecialPrice { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<long> TimeFormatId { get; set; }
    
        public virtual BookingType BookingType { get; set; }
        public virtual Currency Currency { get; set; }
        public virtual DayType DayType { get; set; }
        public virtual HoleType HoleType { get; set; }
        public virtual MemberType MemberType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PriceTaxMapping> PriceTaxMappings { get; set; }
        public virtual Slot Slot { get; set; }
        public virtual TimeFormat TimeFormat { get; set; }
    }
}
