//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GolfCentra.Core.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class SessionActivity
    {
        public long SessionActivityId { get; set; }
        public Nullable<long> LoginHistoryId { get; set; }
        public long SessionActivityPageId { get; set; }
        public Nullable<System.DateTime> ArriveAt { get; set; }
        public string PerformedOn { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public string Info { get; set; }
    
        public virtual LogInHistory LogInHistory { get; set; }
        public virtual SessionActivityPage SessionActivityPage { get; set; }
    }
}
