//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GolfCentra.Core.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class SlotSessionWise
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SlotSessionWise()
        {
            this.BlockSlots = new HashSet<BlockSlot>();
        }
    
        public long SlotSessionWiseId { get; set; }
        public long SessionId { get; set; }
        public long SlotId { get; set; }
        public long BookingTypeId { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BlockSlot> BlockSlots { get; set; }
        public virtual BookingType BookingType { get; set; }
        public virtual Session Session { get; set; }
        public virtual Slot Slot { get; set; }
    }
}
